#DNA

#Python homework
##Counting DNA Nucleotides - A Rapid Introduction to Molecular Biology

def CountNucleotide(seq):
    nucleotides = {"A": 0, "C": 0, "G": 0, "T": 0}
    for n in seq:
        nucleotides[n] += 1
    return nucleotides


DNAString = "TCCTATTACTTGTAAGGCGCTTTGTGCCACGTACGTACAGTACCATCCTACATTGGCATAGGGTGGGTCTACCTGGGATACAGTTTTTTTGTGTAACTCTCAATTCAACACTATGCCAGTAAGGATTCGCCAGAAACAGCTGTCTAAATACCATTGGTCAACGCATTTGCGAGTCGCGGTGGGCTAGCGAAATTGGGTGCTATGGCAAGCTTTAGGTGTCGCACGCCCAAGGGCACAGTCGTACTGATCGCCAACGTTGGGGGAAAGGTCTGGCTAAAACTCAACGGCAGGAAGCTTCAGGGGAAACTTCTTGAAAACACGGTATATGTGAAGAATGTCACGACACAAAAAATCTTTCCTTGCCGTATAATCATTCTCCCCAAGCCACCGGATTCTGTACGGCTGTAATGCCCTTTAATGGGCCAGACCAAGTGTTCCTGTCCGGAGGCGACAGGTGCGTCGATTTGCCGTACAATGGTACCCCTGAACAATGGACCTGCACTAAGGGCGAGTGGAAGCTAAAAATGGATTGATAACCATGGCTTCGAGTATACTCCGCAATCTGATCATGACGAAATTAAGCATCAAGTATGAATATCCCCTGTGTCACGTCAGCGGGACATTCTTGTCCGAACTTATATTGGGCGGGGTTATAGACCAGAGAGTCCGTATCGCTCTGGCTTCTACGGGCCGCATTGAATTATGCAAATAAGAGGAAAAGTTCCCCCTTCTGGCATTCAAAGAGAGGACCATCAAAGCCACGAAGCCGTACATCATGAGTCGGCCTGCTCATCACAACGGAGTCCCACTTCTGAAGGATCTACGCGTGTGTGAGTTGTGAGCACTCCGCGTAGCCGGACCAGTCAGACAATATTGAAGCTG"
result = CountNucleotide(DNAString)
print(' '.join([str(val) for key, val in result.items()]))